### ISSUE TITLE
Picard metrics file deleted

### ISSUE THREAD

**Issue by ewels** [NationalGenomicsInfrastructure/piper#41]
The picard `.metrics` file seems to be being deleted. It's probably marked as an intermediate file and so removed once the step is complete.

**Comment by johandahlberg** [comment]
This is fixed now.

**Comment by ewels** [comment]
Huzzah!

![gif](http://s9.postimg.org/572fuk417/Picard_YES_meme.jpg?noCache=1350239625)

_(get it? Picard metrics..?)_

**Comment by johandahlberg** [comment]
:smile_cat:
