### ISSUE TITLE
Add snpEff

### ISSUE THREAD

**Issue by ewels** [NationalGenomicsInfrastructure/piper#43]
It would be great if we could get GATK to run snpEff by adding the `-o gatk` (see the [snpEff documentation](http://snpeff.sourceforge.net/))

This is fairly urgent as the report scripts look for the snpEff output. Tack!

**Comment by johandahlberg** [comment]
I've started to look into this now @ewels. A question: do you think that adding the `--snpEffFile <snp_eff_output_file>` to the VariantAnnotator would be enough? As compared to running SnpEff in stand-alone mode? The docs for this is available here: https://www.broadinstitute.org/gatk/gatkdocs/org_broadinstitute_gatk_tools_walkers_annotator_VariantAnnotator.php

The main draw-back seems to be that this only reports "the most biologically significant effect listed". Is this enough? Or do you think it's better to report as much as possible?

**Comment by ewels** [comment]
Even better! Thanks..

**Comment by johandahlberg** [comment]
Have you've been using the `snpEff_summary.html` to extract info for the reports or do you want me to run with the `-csvStats` option?

**Comment by parlundin** [comment]
I have been running with the ```-csvStats```option. And yes we are using ```snpEff_summary.htm```to extract info.

**Comment by johandahlberg** [comment]
Ok - there is one problem with that. If I run with the `-csvStats` option there is no `snpEff_summary.htm` generated. So unfortuneatly it does not seem possible to get both. What would you guys prefer?

**Comment by parlundin** [comment]
See my answer was a bit unclear. When running snpEff run without the ```-csvStats``` so the html file will be generated. Sorry for the confusion. I have also tried to generate the pdf file but it seems its not possible to generate pdf and html file in same run.

**Comment by johandahlberg** [comment]
Cool! Then I get it. :smile:

**Comment by ewels** [comment]
We actually scrape both currently as there's one bit of info in the HTML which isn't in the CSV. Very annoying :/

**Comment by johandahlberg** [comment]
I'm not sure I follow. Am I to understand that you use both files? If so which one is the most critical to you to get? It doesn't feel very neat to run the program twice with different arguments to get both but if that's the only way to get around it (short of patching snpEff - I guess) I guess we might have to do that? Or what's your preference @ewels and @parlundin?

**Comment by johandahlberg** [comment]
@parlundin and @ewels - I've now written (I think) most of the code necessary to add snpEff into the WGS pipeline. However, I need to get feedback from you guys about if you want the csv or the html file before I can proceed. I hope to be able to test this next week and have a release out the week after that (but considering that the next few weeks will be extremely busy I'm not 100% I will make that deadline).

**Comment by ewels** [comment]
Sorry for the delay in replying, I'm away at the moment. CSV is the best if we have to choose. Ideally SnpEff should put the missing field (that's in the HTML) into the CSV, maybe we can email the authors about that. 

CSV for now is good though.

Phil

**Comment by johandahlberg** [comment]
Ok. Got it. :+1:

**Comment by johandahlberg** [comment]
Done!
