### ISSUE TITLE
Less memory for samtools sort

### ISSUE THREAD

**Issue by johandahlberg** [NationalGenomicsInfrastructure/piper#48]
Samtools sort uses to much memory when running on 8 cores, thus causing memory overflow problems. Maybe we should make this configurable?

**Comment by johandahlberg** [comment]
Should be solved now.

**Comment by mariogiov** [comment]
Awesome! Does this mean we should try using 8 cores again? I can't recall where we landed on that.

**Comment by johandahlberg** [comment]
I think so yes. *fingers crossed*
