### ISSUE TITLE
Bug: Can't detect 'path' not set for a resource or program

### ISSUE THREAD

**Issue by biocyberman** [NationalGenomicsInfrastructure/piper#50]
I took me a while to pinpoint the issue. 

Currently `path` is not set for `snpEffReference` resource in `uppmax_global_config.xml`.  This causes a vague `java.lang.NullPointerException`. After debugging, I found that method `transformToNamePathMap` could not map snpEffReference resource correctly, and the exception in `getVersionFromKey` is never thrown. Probably exceptions have to be catched in the trait `NameVersionAndPath`, but I have no ideas how to do that yet. One quick fix is to make sure that path to snpEffReference resource is set in  `uppmax_global_config.xml`

**Comment by johandahlberg** [comment]
This is fixed in the devel branch already. Will merge that as soon as I get confirmation from @parlundin  on some other things.

**Comment by biocyberman** [comment]
Thank you @johandahlberg. I only pulled and checked on the master branch so I did not know the bug has been fixed. I will close this then.
