### ISSUE TITLE
Question: is it intentional to leave out minimumBaseQuality from HaplotypeCallerBase?

### ISSUE THREAD

**Issue by biocyberman** [NationalGenomicsInfrastructure/piper#59]
I was checking  /src/main/scala/molmed/utils/VariantCallingUtils.scala and found that the parameter `minimumBaseQuality` is not used for `HaplotypeCallerBase` where it is used in `UnifiedGenotyperSnpCall`. Is this intentional, and what is the rationale for doing that?

**Comment by johandahlberg** [comment]
Well this has to be a miss on my part. Well spotted! Changed this from a question to a bug so that it gets on the todo list.
